### ISSUE TITLE
The Status . . . It Lingers!

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1127]
![Screenshot_20221022-215318](https://user-images.githubusercontent.com/91638992/197375023-303c6615-06c5-44ad-9b2a-e52512470cdc.png)

I slew Tengu using a wand of corrosion & tapping on the spot where the status effect icon was during the fight (below Tengu's health bar) pulls up the description box. This can happen w/ any boss/status effect combo but is most noticeable after this fight because, after centering your hero in the room by grabbing the mask, tapping on the door to leave will usually result in this.

**Comment by 00-Evan** [comment]
I had this reported to me one previously but was unable to reproduce it, will try again.

Can you tell me what effect did the killing damage to Tengu?

**Comment by LeahLuong** [comment]
Huh, I searched but couldn't find a previous bug report, hence why I posted.

I believe the finishing blow came from a throwing spear while Tengu was sitting in the corrosive cloud. Hard to tell if it was that or the cloud that got him but it had to be 1 of those 2.

**Comment by 00-Evan** [comment]
I receive bug reports from a bunch of different channels, probably the largest being email.

**Comment by 00-Evan** [comment]
fixed in commit 233a0323f1b87d216e5a04227b42640563081604

**Comment by LeahLuong** [comment]
![Screenshot_20221029-090021](https://user-images.githubusercontent.com/91638992/198841614-44ead336-af5c-42ad-9e4d-26009ef84159.png)

Seemingly wasn't fixed in 1.4.2. Does "v1.4.2 milestone" mean it's coming in the next update??

**Comment by 00-Evan** [comment]
A fix was attempted in v1.4.2, clearly didn't work. As I mentioned before I wasn't actually able to reproduce the issue, and so had to essentially guess at correcting it.

This one was dwarf king falling to deferred damage, obviously, so I'll take a look at that case.

**Comment by LeahLuong** [comment]
That's right, deferred dmg did the dwarf king in. This issue is fairly reproducible for me on my Android 6.0.1 phone: simply kill a boss while they have an active status effect & tap around for it after the fight. In the latest shot, I went to buy the scroll of LAGUZ & got the description box instead.

I found what's possibly an early example of this in #161. Check brunal's 4th point & he also gives his own specs @ that time. Revisiting your own comments might also give you deeper insight.

**Comment by Wolfman1234567890** [comment]
How many scrolls did you identify at the time and what scroll was it.

**Comment by LeahLuong** [comment]
I'm pretty sure I'd ID'd all 69 scrolls by then & it was a scroll of LAGUZ. Didn't you read my comment or look @ the pretty picture??

**Comment by Pr0methean** [comment]
He means what did LAGUZ turn out to be in that run.

**Comment by 00-Evan** [comment]
This is totally unrelated to #161, the buffs in the boss health bar were only added in v1.3.0 and work under different circumstances than the hero's buffs.

I was able to manually reproduce this by disabling some code (previously it was only triggered by a race condition). Should be properly fixed in the next patch.

**Comment by 00-Evan** [comment]
fixed (for real this time) in commit 95b2a2208b2af46b68009ddff406a886b2c02f70
