### ISSUE TITLE
Infinite turn bug when encountering caster enemies

### ISSUE THREAD

**Issue by kdallasd** [00-Evan/shattered-pixel-dungeon#362]
Had an infinite turn when moving to attack enemy. Was one of the casters.

Closing and reopening app solved.

**Comment by 00-Evan** [comment]
beta issues shouldn't be posted here as there isn't a related source release, so there's no commits for me to reference when the issue is fixed. Conveniently, this isn't a beta exclusive issue and also affects the latest source release, so I've just edited your post.

I am aware of this issue though and hope to have it fixed soon. Its become more common because of the beta.

**Comment by kdallasd** [comment]
Understood. Should beta issues go to the Discord instead?

**Comment by 00-Evan** [comment]
Discord or email works. I'll add a mention of that to the release notes.

**Comment by 00-Evan** [comment]
Fixed as a part of commit ea16ddf02a68d2c02530e8b1d2825f3ee5727644

Relevant changes were in:
core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/effects/MagicMissile.java

**Comment by MiroslavR** [comment]
Unfortunately, this bug is still a thing in 0.8.0. The following screenshot was taken after restarting the game, but the situation during the infinite turn looked the same except the Gnoll Brute was one tile above (restarting moved him down):
![infinite_turn](https://user-images.githubusercontent.com/7346770/80288453-5576f880-8738-11ea-8c5f-65edc99a4dd2.png)


I had just moved to the grass tile where I'm standing in the screenshot before the bug occurred. Maybe it's related to the fact spinners also spawn MagicMissile...

**Comment by 00-Evan** [comment]
There are a number of potential causes for freezing that may or may not be related to MagicMissile. The above cause of freezing (race condition between the emitter being revived and being killed/erased) should be fixed. Reports of freezes were semi-common in the beta before the above code change, and now after a couple of month yours is the first report of freezing. It's possible spinners, brutes, or magic missile have some other issue which prompts a freeze. Please open a new issue rather than assuming it's the exact same bug.

I'll also need more information to go on, was your game able to close normally (via the menu) or did it crash/require you to force close it. Is there any relevant log output (especially if there was a crash)?
