### ISSUE TITLE
0.8.2 not yet on F-Droid

### ISSUE THREAD

**Issue by sluedecke** [00-Evan/shattered-pixel-dungeon#459]
I like open source and I like F-Droid, so I install Shattered Pixel Dungeon from there.  Shouldn't new versions appear there automatically?  So far f-droid is still on 0.8.1a.

Can you have a look at it please?

**Comment by 00-Evan** [comment]
This is caused by F-Droid's build server not working with Gradle 6.5.1 for some reason. I was hoping that they would fix this but it appears that ensuring their build server works with recent versions of Android's build system isn't a priority.

I'll revert to Gradle 6.5 in 0.8.2a, which, conveniently, is about to release. After that we'll *only* need to wait for F-droid's usual lag of a couple days.

**Comment by 00-Evan** [comment]
Reverted to Gradle 6.5. in commit ad44188e70df4a4f70cfa621f856a102b87ca61c , This is fixed on Shattered's end now.

**Comment by sluedecke** [comment]
Thank you for looking into this!

**Comment by Oblomov** [comment]
For some reason, F-Droid still isn't upgrading the APK. The metadata seems to have caught up correctly to the latest to releases (it shows 0.8.2a and b), but no APK are being produced. I'm not sure if this is because the failure to build 0.8.2 prevents building of subsequent releases or because of some other reason, though.

**Comment by 00-Evan** [comment]
According to their [build logs](https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=30&from=&hidebots=0&hideanons=1&hideliu=1&limit=500) F-Droid's last build pass was on the 16th. Nothing to do but wait ¯\_(ツ)_/¯
