### ISSUE TITLE
identify ring on transmutation

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#524]
Not technically a bug given that talent literally says rings are identified "when he picks it up".  However it takes you out of the moment when you use scroll of transmutation on a ring and it stays unidentified until you drop it and pick it back up.

**Comment by 00-Evan** [comment]
Fixed as a part of commit f2e56172d86247203b7139cde04aaad6357ebc1f

**Comment by protective1** [comment]
It seems that this is still happening in 9.2b.  I transmuted a +3 ring and its new type is unknown even though I have the Thief's Intuition +2 talent.
![Screenshot_20210508-191731](https://user-images.githubusercontent.com/8593007/117560442-b0397480-b05b-11eb-8ad0-9bc2690181da.jpg)
![Screenshot_20210508-191720](https://user-images.githubusercontent.com/8593007/117560443-b0397480-b05b-11eb-829a-e01c77562cd6.jpg)

**Comment by 00-Evan** [comment]
please don't necro old issues. This is a separate occurrence of the bug that's already fixed indev.
